/**
 * Build script for the SessionSight Insights SDK.
 *
 * Supports two modes:
 *   bun run build:worker  — generate _worker-bundle.ts only (for dev)
 *   bun run build         — full build (worker + ESM + types + IIFE)
 *
 * The _worker-bundle.ts file is gitignored but required on disk so the
 * dev server can resolve the static import in worker-inline.ts.
 */

import { $ } from 'bun';

const workerOnly = process.argv.includes('--worker-only');

// Phase 1: Build the worker to a standalone minified bundle
const workerResult = await Bun.build({
  entrypoints: ['src/worker.ts'],
  format: 'esm',
  target: 'browser',
  minify: true,
});

if (!workerResult.success) {
  console.error('Failed to build worker:');
  for (const log of workerResult.logs) console.error(log);
  process.exit(1);
}

const workerCode = await workerResult.outputs[0]!.text();
console.log(`Worker bundle: ${(workerCode.length / 1024).toFixed(1)}KB minified`);

// Phase 2: Write the generated bundle module
const bundleSource = `// AUTO-GENERATED by build.ts. Do not edit.\nexport const WORKER_SOURCE = ${JSON.stringify(workerCode)};\n`;
await Bun.write('src/_worker-bundle.ts', bundleSource);
console.log('Generated src/_worker-bundle.ts');

if (workerOnly) {
  console.log('Worker build complete (dev mode).');
  process.exit(0);
}

// Phase 3: Build ESM, declarations, and IIFE
await $`bun build src/index.ts --outdir dist --format esm --target browser`;
await $`bunx tsc --emitDeclarationOnly --declaration --outDir dist`;
await $`bun build src/iife.ts --outfile dist/sessionsight.js --format iife --target browser --minify`;
console.log('Full build complete.');
