/**
 * Build script for the SessionSight Insights SDK.
 *
 * Supports two modes:
 *   bun run build:worker  : generate _worker-bundle.ts only (for dev)
 *   bun run build         : full build (worker + ESM + types + IIFE)
 *
 * The _worker-bundle.ts / _anonymous-worker-bundle.ts files are gitignored
 * but required on disk so the dev server can resolve the static imports in
 * worker-inline.ts and anonymous-worker-inline.ts.
 */

import { $ } from 'bun';

const workerOnly = process.argv.includes('--worker-only');

// Phase 1: Build both workers to standalone minified bundles. Full-tier
// worker carries the WS/visitor-token pipeline; anonymous-tier worker is
// the HTTP-only batched transport for declined / pre-banner traffic.
const workerResult = await Bun.build({
  entrypoints: ['src/worker.ts'],
  format: 'esm',
  target: 'browser',
  minify: true,
});
if (!workerResult.success) {
  console.error('Failed to build worker:');
  for (const log of workerResult.logs) console.error(log);
  process.exit(1);
}
const workerCode = await workerResult.outputs[0]!.text();
console.log(`Worker bundle: ${(workerCode.length / 1024).toFixed(1)}KB minified`);

const anonWorkerResult = await Bun.build({
  entrypoints: ['src/anonymous-worker.ts'],
  format: 'esm',
  target: 'browser',
  minify: true,
});
if (!anonWorkerResult.success) {
  console.error('Failed to build anonymous worker:');
  for (const log of anonWorkerResult.logs) console.error(log);
  process.exit(1);
}
const anonWorkerCode = await anonWorkerResult.outputs[0]!.text();
console.log(`Anonymous worker bundle: ${(anonWorkerCode.length / 1024).toFixed(1)}KB minified`);

// Phase 2: Write the generated bundle modules
const bundleSource = `// AUTO-GENERATED by build.ts. Do not edit.\nexport const WORKER_SOURCE = ${JSON.stringify(workerCode)};\n`;
await Bun.write('src/_worker-bundle.ts', bundleSource);
console.log('Generated src/_worker-bundle.ts');

const anonBundleSource = `// AUTO-GENERATED by build.ts. Do not edit.\nexport const ANONYMOUS_WORKER_SOURCE = ${JSON.stringify(anonWorkerCode)};\n`;
await Bun.write('src/_anonymous-worker-bundle.ts', anonBundleSource);
console.log('Generated src/_anonymous-worker-bundle.ts');

if (workerOnly) {
  console.log('Worker build complete (dev mode).');
  process.exit(0);
}

// Phase 3: Build ESM, declarations, and IIFE
await $`bun build src/index.ts --outdir dist --format esm --target browser`;
await $`bunx tsc --emitDeclarationOnly --declaration --outDir dist`;
await $`bun build src/iife.ts --outfile dist/sessionsight.js --format iife --target browser --minify`;
console.log('Full build complete.');
