/**
 * Creates a Web Worker from the inlined anonymous-tier worker bundle.
 *
 * The ANONYMOUS_WORKER_SOURCE string is imported from _anonymous-worker-bundle.ts,
 * generated by `bun run build:worker` (or the full `bun run build`). Returns
 * `null` when Workers are unavailable or the bundle wasn't built; callers
 * fall back to main-thread HTTP delivery.
 */

import { ANONYMOUS_WORKER_SOURCE } from './_anonymous-worker-bundle.js';

export function createInlineAnonymousWorker(): Worker | null {
  try {
    if (typeof Worker === 'undefined' || !ANONYMOUS_WORKER_SOURCE) return null;
    const blob = new Blob([ANONYMOUS_WORKER_SOURCE], { type: 'application/javascript' });
    const url = URL.createObjectURL(blob);
    const worker = new Worker(url);
    setTimeout(() => URL.revokeObjectURL(url), 0);
    return worker;
  } catch (e) {
    console.warn('SessionSight: failed to create anonymous worker, using main-thread fallback', e);
    return null;
  }
}
